#define OPTION_EXIT 0
#define OPTION_SENO 1
#define OPTION_LOG_10 2
#define OPTION_LOG_LIN 3
#define OPTION_EXP 4
#define OPTION_ESCALON 5
#define OPTION_MRUA 6
#define OPTION_PAR 7

#define OPTION_SAME_PARAM 1
#define OPTION_NEW_PARAM 2

#define OPTION_CONFIR 1